### ISSUE TITLE
Flutter v3.24.1 can not build on Android

### ISSUE THREAD

**Issue by omartinma** [BlinkID/blinkid-flutter#70]
Hi,

I'm currently using in my project the Flutter version 3.19.3. When upgrading to 3.24.1 I'm not able to build the Android project anymore, and I'm seeing this issue. 

What is the maximum Flutter version supported by the library at the moment?

Thanks!

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
ERROR:/Users/myprofile/.gradle/caches/transforms-3/ce81779b4f1a3bd17c8fa4641cb4f760/transformed/jetified-appcompat-resources-1.7.0-runtime.jar: D8: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
ERROR:/Users/myprofile/.gradle/caches/transforms-3/9749eb58411c3c662945afefe8b3d132/transformed/appcompat-1.7.0-runtime.jar: D8: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform appcompat-resources-1.7.0.aar (androidx.appcompat:appcompat-resources:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/myprofile/.gradle/caches/transforms-3/ce81779b4f1a3bd17c8fa4641cb4f760/transformed/jetified-appcompat-resources-1.7.0-runtime.jar.
         > Error while dexing.
   > Failed to transform appcompat-1.7.0.aar (androidx.appcompat:appcompat:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/myprofile/.gradle/caches/transforms-3/9749eb58411c3c662945afefe8b3d132/transformed/appcompat-1.7.0-runtime.jar.
         > Error while dexing.
```

**Comment by somyaguptagit** [comment]
Hi @omartinma Thank you for reaching out! When you say you add both dependencies, do you mean BlinkID+BlinkCard(flutter)? could you also provide us additional logs of the exception?
You can also reach out to us directly at support@microblink.com and we can assist you further.

**Comment by radivojeostojic** [comment]
@omartinma I had a similar issue yesterday, and I had to update the compileSdk to 34 and the Android Gradle Plugin version to 8.1.3 to make it work.

**Comment by mparadina** [comment]
Hi @radivojeostojic and @omartinma 

@radivojeostojic that is correct, updating to Gradle v8 should resolve the issue. Thank you for responding.
I will update this information in the documentation in the upcoming release.

**Comment by omartinma** [comment]
Thanks both for your replies @radivojeostojic @mparadina.

Actually, I was using Gradle 8.7 with Android Gradle Plugin 8.5. I tried to use 8.1.3 and I'm still getting the same error when I combine the 2 libraries. If I use blinkid_flutter only I can run the project perfectly.

**Comment by omartinma** [comment]
Do we have any update about this topic? @somyaguptagit @mparadina Thanks!
